---
title: "R OpenSci ozunconference 2017 Projects"
output: html_document
---

### `r emo::ji("road")` [ozroaddeaths - Pull data from the Australian Road Deaths Database](https://github.com/ropenscilabs/ozroaddeaths)

### `r emo::ji("road")` [ozroaddeaths - Pull data from the Australian Road Deaths Database](https://github.com/ropenscilabs/ozroaddeaths)

### `r emo::ji("time")` [realtime - Plot real time events](https://github.com/ropenscilabs/realtime)

### `r emo::ji("line")` [realtime - Plot real time events](https://github.com/ropenscilabs/realtime)

### `r emo::ji("aeroplane")` [ozflights - pull Aviation data from BITRE ](https://github.com/ropenscilabs/ozflights)

### `r emo::ji("rocket")` [icon - easily insert web icons](https://github.com/ropenscilabs/icon)

### `r emo::ji("clock")` [stow - simple version control in R](https://github.com/ropenscilabs/ozrepro)

### `r emo::ji("cricket")` [cricinfo - access cricket data from crickinfo ](https://github.com/ropenscilabs/cricinfo)

### `r emo::ji("fire")` [ronfhir - makes data available in R from servers that follow the FHIR format](https://github.com/ropenscilabs/ronfhir)

### `r emo::ji("graph")` [styles - themes for base plots](https://github.com/ropenscilabs/styles)

### `r emo::ji("australia")` `r emo::ji("woman")` `r emo::ji("football")` [AFLW - AFL Womens](https://github.com/ropenscilabs/ozwomensport/tree/master/AFLW)

### `r emo::ji("australia")` `r emo::ji("football")` [AFLW - AFL Data](https://github.com/ropenscilabs/)

### `r emo::ji("australia")` `r emo::ji("paint")` [ochRe](https://github.com/ropenscilabs/ochRe)

### `r emo::ji("house")` [datagovau](https://github.com/ropenscilabs/datagovau)

---

If there are any projects that you know are missing please
[fork](https://github.com/ropenscilabs/ozunconf-projects) 
this document on GitHub, make changes, and then send a pull
request.
